config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  get "profile" => "pages#profile"
  get "dashboard" => "pages#dashboard"

  resources :flats do
    resources :slots, only: [:create, :update, :destroy] do
      patch "slot_confirm" => "slots#slot_confirm"
      patch "slot_cancel" => "slots#slot_cancel"
    end
    get "visits" => "flats#visits"
    get "dossiers" => "flats#dossiers"
    patch "filter" => "flats#filter"
    get "reservations" => "flats#reservations"
    resources :bookings, only: [] do
      patch "booking_confirm" => "bookings#booking_confirm"
      patch "booking_cancel" => "bookings#booking_cancel"
    end
  end
  mount Attachinary::Engine => "/attachinary"
end

app/models/flat.rb
class Flat < ApplicationRecord
  geocoded_by :address
  after_validation :geocode, if: :address_changed?

  belongs_to :landlord, foreign_key: :landlord_id, class_name: "User"
  has_many :slots, dependent: :destroy
  has_many :bookings, dependent: :destroy

  has_attachments :photos, maximum: 10

  validates :title, :description,  :availability_date, :min_duration, :address, :size, :rent, :rental_costs, :floor, :rooms, :bedrooms, presence: true
  validates :status, presence: true, inclusion: { in: ["Available","Busy"] }
  validates :rental_type, presence: true, inclusion: { in: ["Colocation","Location"] }
end

app/helpers/flats_helper.rb
module FlatsHelper
  def set_flat_image(flat)
    flat.photos.size == 0 ? cl_image_tag(asset_path('default_flat.png')) : cl_image_tag(flat.photos.first.path, :alt => "banner_image", height:300, width: 720, crop: :fill)
  end

  def set_number(string)
    a = string.split
    "#{a[1]} (#{a[0]})"
  end
end

app/views/flats/modals/_modal_candidates_bookings.html.erb
<div class="modal fade bs-example-modal-lg" id="modal-booking-<%= booking.id %>" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel">
  <div class="modal-dialog modal-lg" role="document">
    <div class="modal-content">

      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title text-center" id="myModalLabel"><strong>Profil de <%= set_fullname(booking.tenant) %></strong></h4>
      </div>

      <div class="modal-body">

        <% if booking.status == "Pending" %>

          <h5><%= set_fullname(booking.tenant) %> est intéressé par votre bien.</h5>
          <h5>Il attend que vous choisissiez ce dossier pour devenir votre locataire. </h5>

          <div class="text-center">Note du Dossier : <%= render 'flats/grade', booking: booking, user: booking.tenant, flat: @flat %></div>

          <div><%= image_tag set_user_photo(booking.tenant), class: "card-candidates-user avatar-large-square" %></div>
          <div>Prénom : <%= booking.tenant.first_name %></div>
          <div>Nom : <%= booking.tenant.last_name %></div>
          <div>Situation Professionnelle : <br><%= booking.tenant.status %></div>
          <div><%= booking.tenant.description %></div>

          <div class="modal-footer">
            <button type="button" class="btn btn-red" data-toggle="modal" href="#modal-confirm-bookings<%= booking.id %>" data-dismiss="modal">Choisir ce locataire</button>
          </div>


        <% elsif booking.status == "Confirmed" %>

          <h5>Vous avez choisi <%= set_fullname(booking.tenant) %></h5>
          <h5>pour être le locataire de votre bien.</h5>
          <h5>Vous pouvez changer d'avis et refuser ce dossier</h5>

          <div class="text-center">Note du Dossier : <%= render 'flats/grade', booking: booking, user: booking.tenant, flat: @flat %></div>

          <div><%= image_tag set_user_photo(booking.tenant), class: "card-candidates-user avatar-large-square" %></div>
          <div>Prénom : <%= booking.tenant.first_name %></div>
          <div>Nom : <%= booking.tenant.last_name %></div>
          <div>Situation Professionnelle : <br><%= booking.tenant.status %></div>
          <div><%= booking.tenant.description %></div>

          <div class="modal-footer">
            <button type="button" class="btn btn-red" data-toggle="modal" href="#modal-confirm-bookings<%= booking.id %>" data-dismiss="modal">Changez de locataire</button>
          </div>


        <% else %>

          <h5>Vous avez refuser le dossier de <%= set_fullname(booking.tenant) %></h5>
          <h5>Vous pouvez le recontacter si vous souhaitez.</h5>

          <div class="text-center">Note du Dossier : <%= render 'flats/grade', booking: booking, user: booking.tenant, flat: @flat %></div>

          <div><%= image_tag set_user_photo(booking.tenant), class: "card-candidates-user avatar-large-square" %></div>
          <div>Prénom : <%= booking.tenant.first_name %></div>
          <div>Nom : <%= booking.tenant.last_name %></div>
          <div>Situation Professionnelle : <br><%= booking.tenant.status %></div>
          <div><%= booking.tenant.description %></div>

          <div class="modal-footer">
            <button type="button" class="btn btn-red" data-toggle="modal" href="#modal-confirm-bookings<%= booking.id %>" data-dismiss="modal">Choisir ce locataire</button>
          </div>


        <% end %>

      </div>

    </div>
  </div>
</div>

app/views/flats/modals/_modal_candidates_slots.html.erb
<div class="modal fade bs-example-modal-lg" id="modal-slot-<%= slot.id %>" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel">
  <div class="modal-dialog modal-lg" role="document">
    <div class="modal-content">

      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title text-center" id="myModalLabel"><strong>Profil de <%= set_fullname(slot.tenant) %></strong></h4>
      </div>

      <div class="modal-body">

        <% if slot.starts_at - Time.now > 0 %>

          <h5><%= set_fullname(slot.tenant) %> est intéressé par votre bien.</h5>
          <h5>Il attend que vous choisissiez ce dossier pour devenir votre locataire. </h5>

          <div class="text-center">Note du Dossier : <%= render 'flats/grade', slot: slot, user: slot.tenant, flat: @flat %></div>

          <div><%= image_tag set_user_photo(slot.tenant), class: "card-candidates-user avatar-large-square" %></div>
          <div>Prénom : <%= slot.tenant.first_name %></div>
          <div>Nom : <%= slot.tenant.last_name %></div>
          <div>Situation Professionnelle : <br><%= slot.tenant.status %></div>
          <div><%= slot.tenant.description %></div>

          <div class="modal-footer">
            <button type="button" class="btn btn-danger" data-toggle="modal" href="#modal-confirm-slots<%= slot.id %>" data-dismiss="modal">Annuler la visite</button>
          </div>

        <% else %>

          <h5>Vous avez refuser le dossier de <%= set_fullname(slot.tenant) %></h5>
          <h5>Vous pouvez le recontacter si vous souhaitez.</h5>

          <div class="text-center">Note du Dossier : <%= render 'flats/grade', slot: slot, user: slot.tenant, flat: @flat %></div>

          <div><%= image_tag set_user_photo(slot.tenant), class: "card-candidates-user avatar-large-square" %></div>
          <div>Prénom : <%= slot.tenant.first_name %></div>
          <div>Nom : <%= slot.tenant.last_name %></div>
          <div>Situation Professionnelle : <br><%= slot.tenant.status %></div>
          <div><%= slot.tenant.description %></div>

          <div class="modal-footer">
            <button type="button" class="btn btn-default" data-dismiss="modal">Retour</button>
          </div>


        <% end %>

      </div>

    </div>
  </div>
</div>

app/views/flats/modals/_modal_confirm_bookings.html.erb
<div class="modal fade" tabindex="-1" role="dialog" id="modal-confirm-bookings<%= booking.id %>">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title">Confirmez votre choix !</h4>
      </div>

        <% if booking.status == "Pending" %>

          <div class="modal-body">
            <p>Vous êtes sur le point de choisir ce locataire.</p>
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-default" data-dismiss="modal">Retour</button>

            <%= simple_form_for [@flat, booking], url: flat_booking_booking_confirm_path(@flat, booking), method: :patch do |f| %>
              <%= f.submit "Choisir ce locataire !", class: "btn btn-red" %>
            <% end %>

          </div>

        <% elsif booking.status == "Confirmed" %>

          <div class="modal-body">
            <p>Vous êtes sur le point d'annuler cette réservation.</p>
            <p>Si vous confirmez, vous pourrez changer de locataire.</p>
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-default" data-dismiss="modal">Retour</button>

            <%= simple_form_for [@flat, booking], url: flat_booking_booking_cancel_path(@flat, booking), method: :patch do |f| %>
              <%= f.submit "J'annule cette réservation !", class: "btn btn-red" %>
            <% end %>

          </div>

        <% else %>

          <div class="modal-body">
            <p>Vous êtes sur le point de choisir ce locataire.</p>
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-default" data-dismiss="modal">Retour</button>

            <%= simple_form_for [@flat, booking], url: flat_booking_booking_confirm_path(@flat, booking), method: :patch do |f| %>
              <%= f.submit "Choisir ce locataire !", class: "btn btn-red" %>
            <% end %>

          </div>

        <% end %>

    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

app/views/flats/modals/_modal_confirm_slots.html.erb
<div class="modal fade" tabindex="-1" role="dialog" id="modal-confirm-slots<%= slot.id %>">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title">Confirmez votre choix !</h4>
      </div>

        <% if slot.status == "Booked" %>

          <div class="modal-body">
            <p>Vous êtes sur le point d'annuler cette visite.</p>
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-default" data-dismiss="modal">Retour</button>

            <%= simple_form_for [@flat, slot], url: flat_slot_slot_cancel_path(@flat, slot), method: :patch do |f| %>
              <%= f.submit "J'annule cette visite !", class: "btn btn-red" %>
            <% end %>

          </div>

       <!--  <#% else %>

          <div class="modal-body">
            <p></p>
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-red" data-dismiss="modal"></button>
            <button type="button" class="btn btn-red" data-dismiss="modal"></button>
          </div> -->

        <% end %>

    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->