config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  get "profile" => "pages#profile"
  get "dashboard" => "pages#dashboard"

  resources :flats do
    resources :slots, only: [:create, :update, :destroy] do
      patch "slot_confirm" => "slots#slot_confirm"
      patch "slot_cancel" => "slots#slot_cancel"
    end
    get "visits" => "flats#visits"
    get "dossiers" => "flats#dossiers"
    patch "filter" => "flats#filter"
    get "reservations" => "flats#reservations"
    resources :bookings, only: [] do
      patch "booking_confirm" => "bookings#booking_confirm"
      patch "booking_cancel" => "bookings#booking_cancel"
    end
  end
  mount Attachinary::Engine => "/attachinary"
end

app/models/flat.rb
class Flat < ApplicationRecord
  geocoded_by :address
  after_validation :geocode, if: :address_changed?

  belongs_to :landlord, foreign_key: :landlord_id, class_name: "User"
  has_many :slots, dependent: :destroy
  has_many :bookings, dependent: :destroy

  has_attachments :photos, maximum: 10

  validates :title, :description,  :availability_date, :min_duration, :address, :size, :rent, :rental_costs, :floor, :rooms, :bedrooms, presence: true
  validates :status, presence: true, inclusion: { in: ["Available","Busy"] }
  validates :rental_type, presence: true, inclusion: { in: ["Colocation","Location"] }
end

app/helpers/flats_helper.rb
module FlatsHelper
  def set_flat_image(flat)
    flat.photos.size == 0 ? cl_image_tag(asset_path('default_flat.png')) : cl_image_tag(flat.photos.first.path, :alt => "banner_image", height:300, width: 720, crop: :fill)
  end

  def set_number(string)
    a = string.split
    "#{a[1]} (#{a[0]})"
  end
end

app/views/flats/_grade.html.erb
<% if set_grade(user, flat) >= 5 %>

  <% 5.times do %>
    <i class="fa fa-star" aria-hidden="true"></i>
  <% end %>

<% elsif set_grade(user, flat) <= 0 %>

  <% 5.times do %>
    <i class="fa fa-star-o" aria-hidden="true"></i>
  <% end %>

<% elsif set_grade(user, flat) == set_grade(user, flat).floor %>

  <% set_grade(user, flat).floor.times do %>
    <i class="fa fa-star" aria-hidden="true"></i>
  <% end %>
  <% (5 - set_grade(user, flat).floor).times do %>
    <i class="fa fa-star-o" aria-hidden="true"></i>
  <% end %>

<% else %>

  <% set_grade(user, flat).floor.times do %>
    <i class="fa fa-star" aria-hidden="true"></i>
  <% end %>
  <i class="fa fa-star-half-o" aria-hidden="true"></i>
  <% (4 - set_grade(user, flat).floor).times do %>
    <i class="fa fa-star-o" aria-hidden="true"></i>
  <% end %>

<% end %>

app/views/flats/_pickvisitform.html.erb
<div id="datepicker-slots"></div>
<% @flat.slots.each do |slot| %>
  <%= simple_form_for([@flat, slot], html:{ class: "hidden slot-form", "data-date" => slot.starts_at.strftime("%d/%m/%Y")}) do |f|%>
    <%= f.error_notification %>
    <% if slot.status == "Booked" %>
      <%= f.button :submit, slot.starts_at.strftime("%A at %H:%M | Déjà réservé"), disabled: true, class:"btn slot"%>
    <% else %>
      <%= f.button :submit, slot.starts_at.strftime("%A at %H:%M"), class:"btn slot"%>
    <% end %>
  <% end %>
<% end %>

app/views/flats/dossiers.html.erb
<!-- Flat navbar -->
<div class="navbar-flat navbar-flat-wagon-fixed">
  <div class="navbar-flat-content">
    <div class="<%= 'active' if current_page?(edit_flat_path(@flat)) %>">
      <%= link_to "Annonce", edit_flat_path(@flat), class: "navbar-wagon-link" %>
    </div>
    <div class="<%= 'active' if current_page?(flat_dossiers_path(@flat)) %>">
      <%= link_to "Candidats", flat_dossiers_path(@flat), class: "navbar-wagon-link" %>
    </div>
    <div class="<%= 'active' if current_page?(flat_visits_path(@flat)) %>">
      <%= link_to "Visites", flat_visits_path(@flat), class: "navbar-wagon-link" %>
    </div>
    <div class="<%= 'active' if current_page?(flat_reservations_path(@flat)) %>">
      <%= link_to "Réservations", flat_reservations_path(@flat), class: "navbar-wagon-link" %>
    </div>
  </div>
</div>


<div class="container">
  <div class="row">

    <div class="col-xs-12" id="criteres">
          <h1 class="text-center">Vos exigences</h1>

          <div class="text-center card-critere">

            <%= simple_form_for @flat, method: 'patch', url: flat_filter_path(@flat) do |f| %>

            <div class="row texte-center">
              <div class="col-xs-3">
                <%= f.label :income_ratio, "Ratio minimum Salaire du locataire / Loyer :", class: "control-label" %>

                <%= f.input :income_ratio, label: false, class: "form-control", input_html: {value: @flat.income_ratio, min: '1', max: '10', step: '0.1' } %>

                <div class="hidden" id="rent"><%= @flat.rent + @flat.rental_costs %></div>
                <div>soit un salaire minimun :</div>
                <div id="income"><%= (@flat.income_ratio * (@flat.rent + @flat.rental_costs)).round(0) %> €</div>
              </div>

              <div class="col-xs-4">
                <%= f.input :has_warrantor, label: "Garant",
                :collection => [[true, 'Oui'], [false, 'Non']],
                :label_method => :last,
                :value_method => :first,
                :as => :radio_buttons,
                :item_wrapper_class => 'inline',
                :checked => @flat.has_warrantor %>

                <div class="hidden" id="warrantor-income-box">
                  <%= f.input :warrantor_income_ratio, label: "Ratio minimum Salaire du garant / Loyer :", input_html: {value: @flat.warrantor_income_ratio, min: '1', max: '10', step: '0.1' } %>
                  <div>soit un salaire minimun du garant :</div>
                  <div id="warrantor-income"><%= @flat.warrantor_income_ratio * (@flat.rent + @flat.rental_costs) %> €</div>
                </div>

              </div>



              <div class="col-xs-4">
                <%= f.input :deposit, label: "Vous exigez une caution de :", input_html: {value: @flat.deposit, min: '0' , max: ((@flat.rent + @flat.rental_costs) * 2).to_s , step: '10' } %>


                <div id="message-modif"></div>

              </div>

            </div>
            <div class="row">

              <div class="col-xs-12"><%= f.button :submit, "Filtrer", class:"btn btn-red"%>
            <% end %></div>

            </div>

          </div>

        </div>

  </div>
  <div class="row">

    <div class="col-xs-12">
      <div id="candidates" class="marged-top">

        <div id="candidates-bookings" class="<%= 'hidden' if @bookings_confirmed.first.nil? && @bookings_pending.first.nil? %>">
          <h2 class="highlight"><%= set_number(pluralize @bookings_pending.size, "Réservation") %></h2>
          <div id="candidates-bookings-confirmed">
            <%= render 'flats/candidates/candidates_bookings_confirmed', bookings_confirmed: @bookings_confirmed, flat: @flat %>
          </div>
          <div id="candidates-bookings-pending">
            <%= render 'flats/candidates/candidates_bookings_pending', bookings_pending: @bookings_pending, flat: @flat %>
          </div>
        </div>

        <div id="candidates-slots" class="<%= 'hidden' if @slots_booked.first.nil? %>">
          <h2 class="highlight"><%= set_number(pluralize @slots_booked.count, "Visites") %></h2>
          <div id="candidates-slots-booked">
            <%= render 'flats/candidates/candidates_slots_booked', slots_booked: @slots_booked, flat: @flat %>
          </div>
        </div>

      </div>
    </div>



  </div>
</div>

<%= content_for(:after_js) do %>
  <script>
    $(document).ready(function() {
      <% if @flat.has_warrantor %>
        $('#warrantor-income-box').removeClass('hidden');
      <% end %>
    });
  </script>
<% end %>

app/views/flats/edit.html.erb
<!-- Flat navbar -->
<div class="navbar-flat navbar-flat-wagon-fixed">
  <div class="navbar-flat-content">
    <div class="<%= 'active' if current_page?(edit_flat_path(@flat)) %>">
      <%= link_to "Annonce", edit_flat_path(@flat), class: "navbar-wagon-link" %>
    </div>
    <div class="<%= 'active' if current_page?(flat_dossiers_path(@flat)) %>">
      <%= link_to "Candidats", flat_dossiers_path(@flat), class: "navbar-wagon-link" %>
    </div>
    <div class="<%= 'active' if current_page?(flat_visits_path(@flat)) %>">
      <%= link_to "Visites", flat_visits_path(@flat), class: "navbar-wagon-link" %>
    </div>
    <div class="<%= 'active' if current_page?(flat_reservations_path(@flat)) %>">
      <%= link_to "Réservations", flat_reservations_path(@flat), class: "navbar-wagon-link" %>
    </div>
  </div>
</div>

<div class="container text-center">
  <div class="row">
    <div class="col-xs-12">
      <div class="card">
        <h2 class="sm-marged-bottom highlight">Partager mon annonce</h2>
        <div class="text-center" style="display: flex; justify-content: center;">
          <textarea class="js-copytextarea textarea-small sm-marged-bottom"><%= "http://www.zenkey.co/flats/#{@flat.id}" %></textarea>
          <button class="js-textareacopybtn sm-marged-bottom" style="margin-left: -32px">
            <i class="fa fa-clone" aria-hidden="true"></i>
          </button>
        </div>
        <%= link_to "Editer", "#", class: "btn btn-red", id: "form-flat-edit-button" %></span>
      </div>
    </div>
  </div>
</div>

<div class="container padded top">
  <div class="row">
    <div class="form col-xs-12">
      <div class="card form-flat-edit hidden">
        <div class="row">
          <h2 class="text-center highlight">Votre annonce</h2>
          <div class="form-flat col-xs-12 col-md-6 col-md-offset-3">
            <%= simple_form_for(@flat) do |f| %>
              <%= f.error_notification %>
              <div class="form-inputs">
                <%= f.input :title,  label: "Titre de l'annonce", required: true %>

                <label class="control-label select required" for="flat_rental_type"> Type de location</label>
                <div class="row">
                  <div class="col-xs-9">
                      <select class="form-control select required" name="flat[rental_type]" id="flat_rental_type">
                        <option value="Location">Location</option>
                        <option value="Colocation">Colocation</option>
                      </select>
                    </div>
                    <!-- f.input :rental_type, label: "Type de location", collection: ["Location", "Colocation"], include_blank: true %> -->
                  <div class="col-xs-3">
                    <div class="checkbox">
                      <input value="<%= @flat.furnished == true ? 1 : 0 %>" type="hidden" name="flat[furnished]">
                      <input class="hidden" type="checkbox" value="<%= @flat.furnished == true ? 0 : 1 %>" name="flat[furnished]" id="flat_furnished">
                      <label class="boolean optional flat-form-choice <%= @flat.furnished == true ? "active" : "" %>" for="flat_furnished">Meublé</label>
                    </div>
                  </div>
                </div>

                <!-- Availability date and minimum duration -->
                <div class="row">
                  <div class="col-xs-12 col-md-6">
                    <%= f.input :availability_date, label: "Date de disponibilité", required: true, as: :string, input_html: { class: "datepicker" } %>
                  </div>
                  <div class="col-xs-12 col-md-6">
                    <%= f.input :min_duration, label: "Durée minimum (mois)", input_html: { value: 1, min: 1, step: 'any' }, required: true %>
                  </div>
                </div>

                <%= f.input :photos, as: :attachinary %>

                <!-- Address -->
                <div class="row">
                  <div class="col-xs-9">
                    <%= f.input :address, label: "Adresse" %>
                  </div>
                  <div class="col-xs-3">
                    <label></label>
                    <div class="checkbox">
                      <input value="<%= @flat.is_address_public == true ? 1 : 0 %>" type="hidden" name="flat[is_address_public]">
                      <input class="hidden " type="checkbox" value="<%= @flat.is_address_public == true ? 0 : 1 %>" name="flat[is_address_public]" id="flat_is_address_public">
                      <label class="boolean optional flat-form-choice <%= @flat.is_address_public == true ? "active" : "" %>" for="flat_is_address_public">Publique</label>
                    </div>
                  </div>
                </div>

                <%= f.input :subway, label: "Métro à proximité", collection: @metro_stations %>
                <%= f.input :size, label: "Superficie", input_html: { value: 9, min: 9, step: 'any' }, required: true %>
                <%= f.input :description, label: "Description", required: true %>

                <!-- Rent and rental costs -->
                <div class="row">
                  <div class="col-xs-6 col-md-6">
                    <%= f.input :rent, label: "Loyer", placeholder: "Montant du loyer", required: true, default: 0 %>
                  </div>
                  <div class="col-xs-6 col-md-6">
                  <%= f.input :rental_costs, label: "Charges locatives", placeholder: "Montant des charges", required: true, default: 0 %>
                  </div>
                </div>

                <!-- f.input :floor, label: "Etage", as: :radio_buttons, collection: [0, 1, 2, 3, 4, 5, 6, 7], required: true -->
                <!-- Radio buttons for the floor -->
                <div class="form-group radio_buttons required flat_floor">
                  <label class="control-label radio_buttons required">Etage</label>
                  <input type="hidden" name="flat[floor]" value="<%= @flat.floor %>">
                  <div class="flat-radio-buttons">
                    <div class="radio flat-radio-button <%= @flat.floor == 0 ? "active" : "" %>">
                      <input class="radio_buttons required hidden " required="required" aria-required="true" type="radio" value="0" name="flat[floor]" id="flat_floor_0">
                      <label for="flat_floor_0">RDC</label>
                    </div>
                    <div class="radio flat-radio-button <%= @flat.floor == 1 ? "active" : "" %>">
                      <input class="radio_buttons required hidden " required="required" aria-required="true" type="radio" value="1" name="flat[floor]" id="flat_floor_1">
                      <label for="flat_floor_1">1</label>
                    </div>
                    <div class="radio flat-radio-button <%= @flat.floor == 2 ? "active" : "" %>">
                      <input class="radio_buttons required hidden " required="required" aria-required="true" type="radio" value="2" name="flat[floor]" id="flat_floor_2">
                      <label for="flat_floor_2">2</label>
                    </div>
                    <div class="radio flat-radio-button <%= @flat.floor == 3 ? "active" : "" %>">
                      <input class="radio_buttons required hidden " required="required" aria-required="true" type="radio" value="3" name="flat[floor]" id="flat_floor_3">
                      <label for="flat_floor_3">3</label>
                    </div>
                    <div class="radio flat-radio-button <%= @flat.floor == 4 ? "active" : "" %>">
                      <input class="radio_buttons required hidden " required="required" aria-required="true" type="radio" value="4" name="flat[floor]" id="flat_floor_4">
                      <label for="flat_floor_4">4</label>
                    </div>
                    <div class="radio flat-radio-button <%= @flat.floor == 5 ? "active" : "" %>">
                      <input class="radio_buttons required hidden " required="required" aria-required="true" type="radio" value="5" name="flat[floor]" id="flat_floor_5">
                      <label for="flat_floor_5">5</label>
                    </div>
                    <div class="radio flat-radio-button <%= @flat.floor == 6 ? "active" : "" %>">
                      <input class="radio_buttons required hidden " required="required" aria-required="true" type="radio" value="6" name="flat[floor]" id="flat_floor_6">
                      <label for="flat_floor_6">6</label>
                    </div>
                    <div class="radio flat-radio-button">
                      <input class="radio_buttons required hidden" required="required" aria-required="true" type="radio" value="7" name="flat[floor]" id="flat_floor_7">
                      <label for="flat_floor_7">7</label>
                    </div>
                  </div>
                </div>

                <!-- Number of rooms and bedrooms -->
                <div class="row">
                  <div class="col-xs-12 col-md-6">
                    <%= f.input :rooms, label: "Nombre de pièces", input_html: { value: 0, min: 0, step: 'any' }, required: true %>
                  </div>
                  <div class="col-xs-12 col-md-6">
                    <%= f.input :bedrooms, label: "Nombre de chambres", input_html: { value: 0, min: 0, step: 'any' }, required: true %>
                  </div>
                </div>

                <!-- Plus -->
                <label class="control-label">Autres caractéristiques</label>
                <div class="flat-form-choices">
                  <div class="checkbox">
                    <input value="<%= @flat.balcony == true ? 1 : 0 %>" type="hidden" name="flat[balcony]">
                    <input class="hidden " type="checkbox" value="<%= @flat.balcony == true ? 0 : 1 %>" name="flat[balcony]" id="flat_balcony">
                    <label class="boolean optional flat-form-choice <%= @flat.balcony == true ?  "active" : "" %>" for="flat_balcony">Balcon</label>
                  </div>
                  <div class="checkbox">
                    <input value="<%= @flat.elevator == true ? 1 : 0 %>" type="hidden" name="flat[elevator]">
                    <input class="hidden" type="checkbox" value="<%= @flat.elevator == true ? 0 : 1 %>" name="flat[elevator]" id="flat_elevator">
                    <label class="boolean optional flat-form-choice <%= @flat.elevator == true ? "active" : "" %>" for="flat_elevator">Ascenseur</label>
                  </div>
                  <div class="checkbox">
                    <input value="<%= @flat.separate_bathroom == true ? 1 : 0 %>" type="hidden" name="flat[separate_bathroom]">
                    <input class="hidden" type="checkbox" value="<%= @flat.separate_bathroom == true ? 0 : 1 %>" name="flat[separate_bathroom]" id="flat_separate_bathroom">
                    <label class="boolean optional flat-form-choice <%= @flat.separate_bathroom == true ?  "active" : "" %>" for="flat_separate_bathroom">WC séparés</label>
                  </div>
                  <div class="checkbox">
                    <input value="<%= @flat.parking == true ? 1 : 0 %>" type="hidden" name="flat[parking]">
                    <input class="hidden" type="checkbox" value="<%= @flat.parking == true ? 0 : 1 %>" name="flat[parking]" id="flat_parking">
                    <label class="boolean optional flat-form-choice <%= @flat.parking == true ?  "active" : "" %>" for="flat_parking">Parking</label>
                  </div>
                </div>
              </div>

              <!-- Form actions -->
              <div class="form-actions text-center">
                <%= f.button :submit, "Editer votre annonce", class:"btn btn-red"%>
              </div>
            <% end %>
          </div>

        </div>
      </div>
    </div>
  </div>
</div>

<% content_for(:after_js) do %>
  <script>
    $(document).ready(function() {
      $("#form-flat-edit-button").click(function(){
        $(".form-flat-edit").toggleClass("hidden");
      });
    });
  </script>
<% end %>

app/views/flats/filter.js.erb
<% if @flat.errors.any? %>
  alert("Vos modifications n'ont pas été enregistrées.");
<% else %>
  $('#candidates-bookings-confirmed').html(" <%= j render 'flats/candidates/candidates_bookings_confirmed', bookings_confirmed: @bookings_confirmed, flat: @flat %> ");
  $('#candidates-bookings-pending').html(" <%= j render 'flats/candidates/candidates_bookings_pending', bookings_pending: @bookings_pending, flat: @flat %> ");
  $('#candidates-slots-booked').html(" <%= j render 'flats/candidates/candidates_slots_booked', slots_booked: @slots_booked, flat: @flat %> ");
  $('#candidates-bookings-cancelled').html(" <%= j render 'flats/candidates/candidates_bookings_cancelled', bookings_cancelled: @bookings_cancelled, flat: @flat %> ");
  $('#candidates-slots-cancelled').html(" <%= j render 'flats/candidates/candidates_slots_cancelled', slots_cancelled: @slots_cancelled, flat: @flat %> ");
  $("#message-modif").show().text('Vos modifications ont bien été enregistrées.').delay(2500).fadeOut();
<% end %>

app/views/flats/reservations.html.erb
<!-- Flat navbar -->
<div class="navbar-flat navbar-flat-wagon-fixed">
  <div class="navbar-flat-content">
    <div class="<%= 'active' if current_page?(edit_flat_path(@flat)) %>">
      <%= link_to "Annonce", edit_flat_path(@flat), class: "navbar-wagon-link" %>
    </div>
    <div class="<%= 'active' if current_page?(flat_dossiers_path(@flat)) %>">
      <%= link_to "Candidats", flat_dossiers_path(@flat), class: "navbar-wagon-link" %>
    </div>
    <div class="<%= 'active' if current_page?(flat_visits_path(@flat)) %>">
      <%= link_to "Visites", flat_visits_path(@flat), class: "navbar-wagon-link" %>
    </div>
    <div class="<%= 'active' if current_page?(flat_reservations_path(@flat)) %>">
      <%= link_to "Réservations", flat_reservations_path(@flat), class: "navbar-wagon-link" %>
    </div>
  </div>
</div>

<div class="container">
  <div class="page-header">
    <h1>Vos réservations</h1>
  </div>

  <div class="row">

        <%= render 'flats/candidates/candidates_bookings_confirmed', bookings_confirmed: @bookings_confirmed, flat: @flat %>

        <%= render 'flats/candidates/candidates_bookings_pending', bookings_pending: @bookings_pending, flat: @flat %>

        <%= render 'flats/candidates/candidates_bookings_cancelled', bookings_cancelled: @bookings_cancelled, flat: @flat %>

  </div>
</div>

app/views/flats/visits.html.erb
<!-- Flat navbar -->
<div class="navbar-flat navbar-flat-wagon-fixed">
  <div class="navbar-flat-content">
    <div class="<%= 'active' if current_page?(edit_flat_path(@flat)) %>">
      <%= link_to "Annonce", edit_flat_path(@flat), class: "navbar-wagon-link" %>
    </div>
    <div class="<%= 'active' if current_page?(flat_dossiers_path(@flat)) %>">
      <%= link_to "Candidats", flat_dossiers_path(@flat), class: "navbar-wagon-link" %>
    </div>
    <div class="<%= 'active' if current_page?(flat_visits_path(@flat)) %>">
      <%= link_to "Visites", flat_visits_path(@flat), class: "navbar-wagon-link" %>
    </div>
    <div class="<%= 'active' if current_page?(flat_reservations_path(@flat)) %>">
      <%= link_to "Réservations", flat_reservations_path(@flat), class: "navbar-wagon-link" %>
    </div>
  </div>
</div>


<div class="container card text-center marged-top">
  <h2 class="highlight">Définir un créneau</h2>
  <div class="row">
    <%= simple_form_for([@flat, @slot]) do |f| %>
    <%= f.error_notification %>
    <div class="col-xs-12 col-sm-6">
      <div style="overflow:hidden;">
        <div class="form-group">
          <div class="col-xs-10 col-xs-offset-1">
            <h4><strong> Début du créneau :</strong></h4>
            <div id="datetimepicker"></div>
          </div>
        </div>
      </div>
    </div>
    <div class="col-xs-12 col-sm-6">
      <h4 class="sm-marged-bottom"><strong> Durée :</strong></h4>
      <div class="form-inputs">
        <%= f.input :starts_at, as: :hidden, :input_html => { :id => "datetimepicker_hidden_field", value: DateTime.now.strftime("%d/%m/%Y %H:%M")} %>
        <div class="col-xs-12">
          <div class="form-group integer optional slot_availability_length form-inline">
            <label class="control-label integer optional" id="label_slot_length" for="slot_availability_length">Créneau de</label>
            <input class="form-control numeric integer optional" value="0" min="0" step="0.5" type="number" name="slot[availability_length]" id="slot_availability_length">
            <span>heures</span>
          </div>
        </div>
        <div class="col-xs-12">
          <div class="form-group integer optional slot_length form-inline sm-marged-bottom">
            <label class="control-label integer optional" id="label_slot_length" for="slot_length">Visites de</label>
            <input class="form-control numeric integer optional" value="0" min="0" step="5" type="number" name="slot[length]" id="slot_length">
            <span>min.</span>
          </div>
        </div>
      </div>
      <div class="form-actions text-center">
        <%= f.button :submit, "Ajouter un créneau", class:"btn btn-red"%>
      </div>
    </div>
    <% end %>
  </div>
</div>

  <!-- Next slots -->
  <% if @flat.slots.order("starts_at asc").where(["status <> 'Cancelled'"]).where(['starts_at >= ?', DateTime.now.midnight]).length >= 1 %>
    <div class="container card text-center">
      <h2 class="highlight">Mes prochaines visites</h2>
      <% @flat.slots.order("starts_at asc").where(["status <> 'Cancelled'"]).where(['starts_at >= ?', DateTime.now.midnight]).group_by{|slot| slot.starts_at.strftime("%A %e %B %Y")}.each do |date, slots| %>
        <h4><strong><%= date %></strong></h4>
        <div class="row">
          <% slots.each do |slot| %>
            <% if slot.status == "Booked" %>
              <div class="col-xs-6 col-sm-3">
                <div class="slot-card-booked" %>
                  <div class="card-description">
                    <p><strong><%= slot.starts_at.strftime(format="%H:%M") %></strong></p>
                    <span>
                      <%= slot.status %>
                      <%= link_to [@flat, slot], data: {:confirm => 'Êtes-vous sûr ?'}, :method => :delete do %>
                        <i class="fa fa-trash" aria-hidden="true"></i>
                      <% end %>
                    </span>
                    <br>
                    <%= cl_image_tag 'https://unsplash.it/400/400', class: "avatar-large" %>
                    <p><%= slot.tenant.email %></p>
                    <p><%= slot.tenant.status %></p>
                  </div>
                </div>
              </div>
            <% elsif slot.status == "Vacant" %>
            <div class="col-xs-6 col-sm-3">
                <div class="slot-card-vacant" %>
                  <div class="card-description">
                    <p><strong><%= slot.starts_at.strftime(format="%H:%M") %></strong></p>
                    <%= slot.status %>
                    <%= link_to [@flat, slot], data: {:confirm => 'Êtes-vous sûr ?'}, :method => :delete do %>
                      <i class="fa fa-trash" aria-hidden="true"></i>
                    <% end %>
                  </div>
                </div>
              </div>
            <% end %>
          <% end %>
        </div>
      <% end %>
    </div>
  <% end %>

  <!-- Past slots -->
  <% if @flat.slots.order("starts_at asc").where(['starts_at < ?', DateTime.now.midnight]).length >= 1 %>
    <div class="container card text-center">
      <h2 class="highlight">Mes visites passées</h2>
      <% @flat.slots.order("starts_at asc").where(['starts_at < ?', DateTime.now.midnight]).group_by{|slot| slot.starts_at.strftime("%A %e %B %Y")}.each do |date, slots| %>
        <h4><strong><%= date %></strong></h4>
        <div class="row">
          <% slots.each do |slot| %>
            <% if slot.status == "Booked" %>
              <div class="col-xs-6 col-sm-3">
                <div class="slot-card-booked" %>
                  <div class="card-category">
                    <p><strong><%= slot.starts_at.strftime(format="%H:%M") %></strong></p>
                  </div>
                  <div class="card-description">
                    <%= cl_image_tag 'https://unsplash.it/400/400', class: "avatar-large" %>
                    <p><%= slot.tenant.email %></p>
                    <p><%= slot.tenant.status %></p>
                  </div>
                </div>
              </div>
            <% else %>
            <div class="col-xs-6 col-sm-3">
                <div class="slot-card-vacant" %>
                  <div class="card-category">
                    <h><strong><%= slot.starts_at.strftime(format="%H:%M") %></strong></p>
                  </div>
                  <div class="card-description">
                    <p><%= slot.status %></p>
                  </div>

                </div>
              </div>
            <% end %>
          <% end %>
        </div>
      <% end %>
    </div>
  <% end %>