config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  get "profile" => "pages#profile"
  get "dashboard" => "pages#dashboard"

  resources :flats do
    resources :slots, only: [:create, :update, :destroy] do
      patch "slot_confirm" => "slots#slot_confirm"
      patch "slot_cancel" => "slots#slot_cancel"
    end
    get "visits" => "flats#visits"
    get "dossiers" => "flats#dossiers"
    patch "filter" => "flats#filter"
    get "reservations" => "flats#reservations"
    resources :bookings, only: [] do
      patch "booking_confirm" => "bookings#booking_confirm"
      patch "booking_cancel" => "bookings#booking_cancel"
    end
  end
  mount Attachinary::Engine => "/attachinary"
end

app/views/pages/dashboard.html.erb
<div class="container padded-top">
  <div class="row">
    <div class="card col-xs-12">
      <h2 class="text-center sm-marged-bottom highlight">Mon dashboard</h2>
        <div class="row">
        <%= link_to new_flat_path do %>
          <div class="col-xs-12 col-sm-4 sm-marged-bottom">
            <div class="card-dashboard flexbox text-center">
                <h2 class="highlight" style= "margin-bottom: 20px">
                  Créer une annonce
                </h2>
            </div>
          </div>
        <% end %>

          <% @user_flats.where(status: "Busy").each do |user_flat|%>
            <%= link_to edit_flat_path(user_flat) do %>
              <div class="col-xs-12 col-sm-4 sm-marged-bottom">
                <div class="card-dashboard">
                  <div class="card-dashboard-image" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url(<%=user_flat.photos.first.nil? ? "" : (cl_image_path user_flat.photos.first.public_id , crop: :scale) %>);">
                    <div class="card-category badge-red"> <%= user_flat.status == "Available" ? "Visites" : "Loué" %> </div>
                    <div>
                        <div class="flat-user-photo">
                         <%= image_tag(set_user_photo(user_flat.booking.tenant)) %>
                        </div>
                    </div>
                  </div>
                  <div class="card-dashboard-description ">
                    <h2 class="highlight"><%= user_flat.title %></h2>
                    <p>
                      <b>Loué depuis le </b><%= user_flat.booking.starting_date %>
                      <b>Fin du bail:</b> <%= user_flat.booking.end_date %>
                      <b>Loyer:</b> <%= user_flat.rent %>
                    </p>
                  </div>
                </div>
              </div>
            <% end %>
          <% end %>

          <% @user_flats.where(status: "Available").each do |user_flat|%>
            <%= link_to edit_flat_path(user_flat) do %>
              <div class="col-xs-12 col-sm-4 sm-marged-bottom">
                <div class="card-dashboard">
                  <div class="card-dashboard-image" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url(<%=user_flat.photos.first.nil? ? "" : (cl_image_path user_flat.photos.first.public_id , crop: :scale) %>);">
                    <div class="card-category badge-red"> <%= user_flat.status == "Available" ? "Visites" : "Loué"  %> </div>
                  </div>
                  <div class="card-dashboard-description ">
                    <h2 class="highlight" style= "margin-bottom: 20px"><%= user_flat.title %></h2>
                    <p> <b>Prochaine visite: </b><%=user_flat.slots.empty? ? "Aucune visite" :user_flat.slots.last.starts_at.strftime("%d/%m/%Y %H:%M") %>
                    <br>
                    <b>Visites a venir ::</b> <%= user_flat.slots.length %>
                    <br>
                    <b>Dossiers déposés :</b> <%= user_flat.bookings.length %>
                    </p>
                  </div>
                </div>
              </div>
            <% end %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/pages/home.html.erb
<!-- Banner -->
<div class="banner" style="background-image: linear-gradient(-225deg, rgba(236, 240, 241,0.2) 0%, rgba(0,36,61,0.6) 50%), url( <%= image_path 'background.jpg' %> );">
  <div class="container">
    <div class="banner-content">
      <h1>Louer mon <span class="typer" data-delay="150" data-words="appartement, logement, chalet, gîte, château" data-colors="white"></span></h1>
      <h1>simplement</h1>
      <p>Trouver un locataire ne devrait pas être si complexe. <br> Zenkey simplifie l'organisation des visites et la recherche d'un locataire</p>
      <% if user_signed_in? %>
        <%= link_to t(".top_call_to_action", default: "Mon dashboard"), dashboard_path, class: "btn btn-red" %>
      <% else %>
        <%= link_to t(".top_call_to_action", default: "Se connecter"), new_user_session_path, class: "btn btn-red" %>
      <% end %>
    </div>
  </div>
</div>

<!-- Features -->
<div class="container">
  <div class="row text-center marged-top">
    <h1>Propriétaires, nous pouvons vous aider</h1>
  </div>
  <div class="row text-center marged-top">
    <div class="col-sm-4 col-xs-12">
      <%= image_tag "feature_annonce.png", class: "feature-img-small" %>
      <h3>Partage de votre annonce</h3>
      <p>Zenkey simplifie la diffusion de votre annonce en vous permettant de la publier sur différents canaux.</p>
    </div>
    <div class="col-sm-4 col-xs-12">
      <%= image_tag "feature_visites.png", class: "feature-img-small" %>
      <h3>Organisation des visites</h3>
      <p>Plus besoin de passer des heures au téléphone pour organiser vos visites. Toutes les visites sont organisées en ligne en fonction de vos disponibilités.</p>
    </div>
    <div class="col-sm-4 col-xs-12">
      <%= image_tag "feature_choix.png", class: "feature-img-small" %>
      <h3>Choix du locataire</h3>
      <p>Les dossiers des locataires sont classés et notés vous permettant de simplifier votre choix.</p>
    </div>
  </div>
</div>