config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  get "profile" => "pages#profile"
  get "dashboard" => "pages#dashboard"

  resources :flats do
    resources :slots, only: [:create, :update, :destroy] do
      patch "slot_confirm" => "slots#slot_confirm"
      patch "slot_cancel" => "slots#slot_cancel"
    end
    get "visits" => "flats#visits"
    get "dossiers" => "flats#dossiers"
    patch "filter" => "flats#filter"
    get "reservations" => "flats#reservations"
    resources :bookings, only: [] do
      patch "booking_confirm" => "bookings#booking_confirm"
      patch "booking_cancel" => "bookings#booking_cancel"
    end
  end
  mount Attachinary::Engine => "/attachinary"
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <title>Zenkey - La location n'a jamais été aussi facile</title>
    <%= favicon_link_tag %>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all' %>
  </head>
  <body>

    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>
    <div class="<%= if current_page?(root_path) || current_page?(dashboard_path) || current_page?(profile_path)
                      'footer-down'
                    else
                      'footer-down-with-flat-navbar'
                    end %>">
      <%= yield %>
    </div>
    <%= render 'shared/footer' %>

    <!-- Javascript script -->
    <!-- Yield after_js for Google maps -->
    <%= javascript_include_tag "https://maps.google.com/maps/api/js?libraries=places&key=#{ENV['GOOGLE_API_BROWSER_KEY']}" %>
    <%= javascript_include_tag "https://cdn.rawgit.com/printercu/google-maps-utility-library-v3-read-only/master/markerclusterer/src/markerclusterer_compiled.js" %>
    <%= javascript_include_tag "https://cdn.rawgit.com/printercu/google-maps-utility-library-v3-read-only/master/infobox/src/infobox_packed.js" %>

    <%= javascript_include_tag 'application' %>

    <!-- Cloudinary script -->
    <%= cloudinary_js_config %>

    <%= yield(:after_js) %>

  </body>
</html>